export const OWNER_GUIDE_GROUPS=['Getting verified','Adding a property','Getting bookable','Managing bookings','Getting paid','Caretakers','Reviews'];
export const ownerGuideArticles=[
 {id:'verification-details',group:'Getting verified',question:'Get your owner account verified',answer:'Add your legal name and address, verify your mobile, and upload a readable PAN, driving licence or masked Aadhaar. Keep every corner visible and avoid glare. Add your own payout details and agree to the owner policies. Review everything before submitting. After submission your details are read-only; a returned application explains what to fix.',href:'/partner/onboarding/details',link:'Open owner verification',screenshot:''},
 {id:'adding-property',group:'Adding a property',question:'Add a property and its photos',answer:'Start with the property type and name. Add the exact address and map pin, facilities, capacity and house rules. Upload at least six clear photos and put your best photo first. Add ownership or authority documents. You can save a draft and come back later.',href:'/partner/listings/new',link:'Add a property',screenshot:'/help/owner/properties.png'},
 {id:'calendar-pricing',group:'Getting bookable',question:'Set prices and open dates for bookings',answer:'Set a weekday and weekend price for each available slot. Check the arrival and departure times and maximum guests. Open dates in the calendar or turn on rolling availability. Closed dates and manual blocks cannot be booked. Submit your property for review; a live property still needs prices and open dates to accept bookings.',href:'/partner/calendar',link:'Open your calendar',screenshot:'/help/owner/pricing.png'},
 {id:'booking-help',group:'Managing bookings',question:'Manage an arrival, cancellation or problem',answer:'Open a booking by its reference and check the visit date and time. Record handover when the guest arrives and return after they leave. Use Get help with this booking for a no-show, cancellation, damage or payment question. Sending a case does not cancel a booking or move money. Record clear evidence and follow the saved status.',href:'/partner/bookings',link:'Open bookings',screenshot:''},
 {id:'getting-paid',group:'Getting paid',question:'Understand earnings and your payout method',answer:'Earnings shows booked rent, collected rent and refunds separately. Test transactions do not represent real bank money. Choose a date range and property to inspect the records or download a statement. Add your own payout method in Settings; changes require a verification code and a new review. Payout sending remains unavailable until a payout provider is configured.',href:'/partner/earnings',link:'Open earnings',screenshot:''},
 {id:'caretakers',group:'Caretakers',question:'Invite the person who opens the gate',answer:'Open Caretakers, enter their name and mobile, and choose their properties. Allow them to record visit evidence or only view arrivals. You can choose whether they see guest contact on the visit day. Rentra sends the invitation when mobile delivery is configured; copy the link if it was not sent. The link expires in 72 hours. Remove access whenever needed; this ends their sessions.',href:'/partner/team',link:'Manage caretakers',screenshot:''},
 {id:'reviews',group:'Reviews',question:'Reply to a guest review or report a problem',answer:'Reviews appear after a completed visit and Rentra’s publication check. Use Needs reply to find unanswered reviews. Write 10–2000 characters and post your public reply; you can edit or delete it later. Keep guest contact details private. Report a policy violation with a specific reason. A report does not automatically hide a review; Rentra sends you its outcome.',href:'/partner/reviews',link:'Open reviews',screenshot:''},
];
